### ISSUE TITLE
modUpdateChecked crashes server, if updates check hangs

### ISSUE THREAD

**Issue by DMahalko** [AbsolemJackdaw/mods#5]
We have a server that uses your code .... somewhere. I don't know which mod, I'm just the admin.

Player logs on. Server stops ticking.

> 2015-01-08 22:05:04 [INFO] [ThirstMod] Successfully loaded stats: JesseWayne21, Level = 16, Saturation = 15.000000
> 2015-01-08 22:05:04 [INFO] Loading Player: JesseWayne21
> 2015-01-08 22:05:04 [INFO] Sending serverside check to: JesseWayne21
> 2015-01-08 22:05:29 [WARNING] The server is going slow. Last server tick was 25275ms ago
> 2015-01-08 22:05:39 [WARNING] The server is going slow. Last server tick was 35277ms ago
> 2015-01-08 22:05:49 [WARNING] The server is going slow. Last server tick was 45278ms ago
> 2015-01-08 22:05:59 [WARNING] The server is going slow. Last server tick was 55279ms ago
> 2015-01-08 22:06:09 [SEVERE] The server has stopped responding!
> (dumps and stops)

Thread log says:

> 2015-01-08 21:35:14 [SEVERE] Current Thread: Server thread
>    PID: 21 | Suspended: false | Native: true | State: RUNNABLE | Blocked Time: -1 | Blocked Count: 92
>    Thread is waiting on monitor(s):
>            Locked on:java.io.BufferedInputStream.read (BufferedInputStream.java:334)
>            Locked on:sun.net.www.protocol.http.HttpURLConnection. getInputStream(HttpURLConnection.java:1323)
>            Locked on:net.minecraft.server.ServerListenThread. func_71766_a(ServerListenThread.java:57)
>    Stack:
>            java.net.SocketInputStream.socketRead0(Native Method)
>            java.net.SocketInputStream.read (SocketInputStream.java:152)
>            java.net.SocketInputStream.read (SocketInputStream.java:122)
>            java.io.BufferedInputStream.fill (BufferedInputStream.java:235)
>            java.io.BufferedInputStream.read1 (BufferedInputStream.java:275)
>            java.io.BufferedInputStream.read (BufferedInputStream.java:334)
>            sun.net.www.http.HttpClient.parseHTTPHeader (HttpClient.java:687)
>            sun.net.www.http.HttpClient.parseHTTP (HttpClient.java:633)
>            sun.net.www.protocol.http.HttpURLConnection. getInputStream(HttpURLConnection.java:1323)
>            java.net.URL.openStream(URL.java:1037)
>            modUpdateChecked.OnPlayerLogin.verifyModVersion(OnPlayerLogin.java:34)
>            modUpdateChecked.OnPlayerLogin.onPlayerLogin (OnPlayerLogin.java:27)
>            cpw.mods.fml.common.registry.GameRegistry. onPlayerLogin(GameRegistry.java:421)
>            cpw.mods.fml.common.network.FMLNetworkHandler. handlePlayerLogin(FMLNetworkHandler.java:299)
>            net.minecraft.server.management.ServerConfigurationManager.func_72355_a(ServerConfigurationManager.java:208)
>            net.minecraft.network.NetLoginHandler.complete Connection (NetLoginHandler.java:223)
>            cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:168)

A Google search for "modUpdateChecked.OnPlayerLogin.verifyModVersion" brings me here to this github.

And what do you know, I go to the website in your code in a web browser, and the page.. takes... forever.. to.. respond..

http://www.dnstechpack.com/user/subaraki/updates.txt

It appears your code does not have a timeout for if the page fails to load in a timely manner, so instead the server crashes.

I have found a temporary solution. I can block the lookup request by making the URL lookup go to localhost:

> /etc/hosts
> 127.0.0.1     localhost    dnstechpack.com    www.dnstechpack.com
> 
> ping dnstechpack.com
> PING localhost (127.0.0.1) 56(84) bytes of data.
> 
> wget http://www.dnstechpack.com/user/subaraki/updates.txt
> 
> --2015-01-08 22:51:59--  http://www.dnstechpack.com/user/subaraki/updates.txt
> Resolving www.dnstechpack.com (www.dnstechpack.com)... 127.0.0.1
> Connecting to www.dnstechpack.com (www.dnstechpack.com)|127.0.0.1|:80... failed: Connection refused.

Result, our server no longer crashes when people logon. Oh, and this now appears in the ForgeModLoader log. Eh.

> 2015-01-08 23:05:44 [INFO] [ForgeModLoader] [ERROR] Couldn't Handle Update. Index 2.

Also why are you doing this every time a new player logs on? Just do it once when the server starts up, with say a 5 second response timeout.

Can you do it asynchronously so the whole server doesn't stop ticking while waiting for the HTTP response?

**Comment by AbsolemJackdaw** [comment]
i removed all the update checkers in all my mods iirc cause they were a pain in the ass. what version are you using, and if i knew what mod, i could remove the checker :)

**Comment by flame-on-coder** [comment]
kind of hard tht code is slopy and most is un needed
